name: dart_extensions
description: Set of method-extensions for dart that makes using framework in a much easier and clean way also adds additional functionality.
version: 2.0.3
documentation: https://github.com/droididan/dart_extentions
homepage: https://github.com/droididan/dart_extentions

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  quiver: ^3.0.0
  http: ^0.13.0
 
  flutter:
    sdk: flutter

dev_dependencies:
  test: 1.17.1 
  