name: dart_extensions
description: Set of method-extensions for dart that makes using framework in a much easier and clean way also adds additional functionality.
version: 1.0.0
documentation: https://github.com/droididan/dart_extentions
homepage: https://github.com/droididan/dart_extentions

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  quiver: ^2.0.0
  http: ^0.12.0+4
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.9.2
  flutter_test:
    sdk: flutter